npm install -g nodemon
npm install -g yo
npm install -g bower
npm install -g react-native-cli
npm install -g generator-keystone
npm install -g coffee-script
npm install -g gulp
npm install -g eslint
npm install -g babel-eslint
npm install -g eslint-plugin-react