npm install -g nodemon
npm install -g yo
npm install -g bower
npm install -g react-native-cli
npm install -g generator-keystone
npm install -g coffee-script
npm install -g gulp
npm install -g jshint
npm install -g jsxhint